version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - .:/app
      - '/app/node_modules'
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql/mysql-server:8.0.23
    restart: always
    ports:
      - '3306:3306'
    expose:
      - '3306'
    command: --init-file /data/application/init.sql --default-authentication-plugin=mysql_native_password
    volumes:
      - ./init.sql:/data/application/init.sql
    environment:
      - MYSQL_DATABASE=db_phonebook
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secretpassword
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

